use dauraksi;
show tables;
desc users;
desc edukasi;
show create table users;
show create table edukasi;
show create table layanan;
show create table hadiah;
desc hadiah;
desc layanan;
select * from users;
select *  from edukasi;
select * from hadiah;
select * from layanan;